name: welcome
description: Keynote de bienvenida en el primer meetup de Flutter Madrid.
version: 1.0.0+1
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_keynote: ^0.1.2
  font_awesome_flutter:
  url_launcher: ^5.4.1
  flare_flutter: ^2.0.1
  flutter_highlight:
  flutter_staggered_animations: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
